name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env: 
      CUDA_VISIBLE_DEVICES: ""
      FORCE_CUDA: "0"
      NO_CUDA: "1"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        export TORCH_CUDA_ARCH_LIST="None"
        pip install -r requirements.txt      
        
    - name: Run tests
      run: pytest tests/test_model.py -v      
